# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cistem_stem <- function(words, case_insensitive) {
    .Call(`_cistem_cistem_stem`, words, case_insensitive)
}

cistem_segment <- function(words, case_insensitive) {
    .Call(`_cistem_cistem_segment`, words, case_insensitive)
}

